name: Cypress Tests (Chrome + Cloud)

on:
  push:
        branches:
            - test/**
        paths-ignore:
            - 'README.md'
            - 'cypress/screenshots/**'
            - 'cypress/videos/**'
            - 'tests/e2e-reports/**'
  pull_request:
        branches:
            - staging
        paths-ignore:
            - 'README.md'
            - 'cypress/screenshots/**'
            - 'cypress/videos/**'
            - 'tests/e2e-reports/**'
  workflow_dispatch: # permite rodar manualmente pelo GitHub
        inputs:
            browsers:
                description: "Escolher navegadores (chrome, edge, firefox, electron)"
                required: false
                default: "chrome"

jobs:
    testes-e2e-cypress:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        strategy:
          matrix:
            browser: [chrome]        
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
            - name: Install dependencies
              run: npm ci

            - name: Verify Cypress installation
              run: npx cypress verify

            - name: Run Cypress tests
              uses: cypress-io/github-action@v5
              with:
                  browser: ${{ matrix.browser }}              
                  record: true                 # envia resultados para o Cypress Dashboard
                  parallel: true              # ajuste se quiser rodar paralelo
                  group: "GitHub Actions - ${{ matrix.browser }}"  # nome do grupo no Dashboard
              env:
                  CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}